###
# index HTML page
GET http://localhost:3000


###
# Finnhub API

# Market news
GET http://localhost:3000/api/v1/market-news




###
# Alpha Vantage API

# Market status
GET http://localhost:3000/api/v1/market-status
