###
# index HTML page
GET http://localhost:3000


# Finnhub API

# MARKET NEWS
###
GET http://localhost:3000/api/v1/market-news

# QUOTE

###
# Get quotes for all markets on the overview
GET http://localhost:3000/api/v1/quotes/overview





# Alpha Vantage API
###
# MARKET STATUS
GET http://localhost:3000/api/v1/market-status
