###
# index HTML page
GET http://localhost:8000


# Finnhub API

# MARKET NEWS
###
GET http://localhost:8000/api/v1/market-news

# QUOTE

###
# Get quotes for a specific index like 'djia' or 'nasdaq'
GET http://localhost:8000/api/v1/quotes/djia
###
GET http://localhost:8000/api/v1/quotes/nasdaq

# COMPANY INFORMATION

###
# Company Profile for symbol
GET http://localhost:8000/api/v1/company-profile/AAPL


# SOCIAL SENTIMENT

###
# Get social sentiment for stocks on Reddit and Twitter. This endpoint is currently in Beta.
GET http://localhost:8000/api/v1/social-sentiment?symbol=AAPL&time_from=yyyy-mm-dd





# Alpha Vantage API
###
# MARKET STATUS
GET http://localhost:8000/api/v1/market-status

###
# NEWS SENTIMENT
GET http://localhost:8000/api/v1/news-sentiment?time_from=20230221
