// struct IndexConsituent {
//     ticker: String,
//     name: String,
// }

pub const DOW_JONES: &'static [(&str, &str)] = &[
    ("JPM", "JPMorgan Chase & Co"),
    ("WBA", "Walgreens Boots Alliance Inc"),
    ("PG", "Procter & Gamble Co"),
    ("GS", "Goldman Sachs Group Inc"),
    ("AAPL", "Apple Inc"),
    ("CAT", "Caterpillar Inc"),
    ("BA", "Boeing Co"),
    ("HON", "Honeywell International Inc"),
    ("MRK", "Merck & Co Inc"),
    ("MMM", "3M Co"),
    ("IBM", "International Business Machines Corp"),
    ("DIS", "Walt Disney Co"),
    ("HD", "Home Depot Inc"),
    ("AMGN", "Amgen Inc"),
    ("V", "Visa Inc"),
    ("INTC", "Intel Corp"),
    ("DOW", "Dow Inc"),
    ("MSFT", "Microsoft Corp"),
    ("TRV", "Travelers Companies Inc"),
    ("JNJ", "Johnson & Johnson"),
    ("KO", "Coca-Cola Co"),
    ("NKE", "Nike Inc"),
    ("MCD", "McDonald's Corp"),
    ("WMT", "Walmart Inc"),
    ("CRM", "Salesforce Inc"),
    ("AXP", "American Express Co"),
    ("UNH", "UnitedHealth Group Inc"),
    ("CVX", "Chevron Corp"),
    ("VZ", "Verizon Communications Inc"),
    ("CSCO", "Cisco Systems Inc"),
];
