// 30 entries
pub const DOW_JONES: &[(&str, &str)] = &[
    ("JPM", "JPMorgan Chase & Co"),
    ("WBA", "Walgreens Boots Alliance Inc"),
    ("PG", "Procter & Gamble Co"),
    ("GS", "Goldman Sachs Group Inc"),
    ("AAPL", "Apple Inc"),
    ("CAT", "Caterpillar Inc"),
    ("BA", "Boeing Co"),
    ("HON", "Honeywell International Inc"),
    ("MRK", "Merck & Co Inc"),
    ("MMM", "3M Co"),
    ("IBM", "International Business Machines Corp"),
    ("DIS", "Walt Disney Co"),
    ("HD", "Home Depot Inc"),
    ("AMGN", "Amgen Inc"),
    ("V", "Visa Inc"),
    ("INTC", "Intel Corp"),
    ("DOW", "Dow Inc"),
    ("MSFT", "Microsoft Corp"),
    ("TRV", "Travelers Companies Inc"),
    ("JNJ", "Johnson & Johnson"),
    ("KO", "Coca-Cola Co"),
    ("NKE", "Nike Inc"),
    ("MCD", "McDonald's Corp"),
    ("WMT", "Walmart Inc"),
    ("CRM", "Salesforce Inc"),
    ("AXP", "American Express Co"),
    ("UNH", "UnitedHealth Group Inc"),
    ("CVX", "Chevron Corp"),
    ("VZ", "Verizon Communications Inc"),
    ("CSCO", "Cisco Systems Inc"),
];

// 95 entries
pub const NASDAQ: &[(&str, &str)] = &[
    ("VRSK", "Verisk Analytics Inc."),
    ("KHC", "Kraft Heinz Co"),
    ("LULU", "Lululemon Athletica Inc"),
    ("XEL", "Xcel Energy Inc"),
    ("EA", "Electronic Arts Inc."),
    ("CMCSA", "Comcast Corp"),
    ("ZM", "Zoom Video Communications Inc"),
    ("MDLZ", "Mondelez International Inc"),
    ("DDOG", "Datadog Inc"),
    ("MNST", "Monster Beverage Corp"),
    ("CDNS", "Cadence Design Systems Inc"),
    ("ILMN", "Illumina Inc"),
    ("ATVI", "Activision Blizzard Inc"),
    ("VRTX", "Vertex Pharmaceuticals Inc"),
    ("TSLA", "Tesla Inc"),
    ("ODFL", "Old Dominion Freight Line Inc."),
    ("SNPS", "Synopsys Inc"),
    ("REGN", "Regeneron Pharmaceuticals Inc"),
    ("LCID", "Lucid Group Inc"),
    ("INTU", "Intuit Inc."),
    ("CHTR", "Charter Communications Inc."),
    ("KDP", "Keurig Dr Pepper Inc."),
    ("ABNB", "Airbnb Inc"),
    ("RIVN", "Rivian Automotive Inc"),
    ("PCAR", "PACCAR Inc"),
    ("KLAC", "KLA Corp"),
    ("AMAT", "Applied Materials Inc"),
    ("BKNG", "Booking Holdings Inc"),
    ("AMZN", "Amazon.com Inc"),
    ("NXPI", "NXP Semiconductors NV"),
    ("DLTR", "Dollar Tree Inc"),
    ("CEG", "Constellation Energy Group Inc"),
    ("QCOM", "Qualcomm Inc"),
    ("MCHP", "Microchip Technology Inc"),
    ("COST", "Costco Wholesale Corp"),
    ("FAST", "Fastenal Co"),
    ("TXN", "Texas Instruments Inc"),
    ("PYPL", "PayPal Holdings Inc"),
    ("MAR", "Marriott International Inc."),
    ("ENPH", "Enphase Energy Inc"),
    ("SBUX", "Starbucks Corp"),
    ("AVGO", "Broadcom Inc"),
    ("EXC", "Exelon Corp"),
    ("ISRG", "Intuitive Surgical Inc"),
    ("ASML", "ASML Holding NV"),
    ("WDAY", "Workday, Inc."),
    ("GFS", "Goldman Sachs Group, Inc. (The)"),
    ("CTSH", "Cognizant Technology Solutions Corporation"),
    ("JD", "JD.com, Inc."),
    ("BKR", "Baker Hughes Company"),
    ("ADI", "Analog Devices, Inc."),
    ("LRCX", "Lam Research Corporation"),
    ("EBAY", "eBay Inc."),
    ("CPRT", "Copart, Inc."),
    ("SIRI", "Sirius XM Holdings Inc."),
    ("CRWD", "CrowdStrike Holdings, Inc."),
    ("GOOG", "Alphabet Inc."),
    ("CSX", "CSX Corporation"),
    ("FTNT", "Fortinet, Inc."),
    ("IDXX", "IDEXX Laboratories, Inc."),
    ("ZS", "Zscaler, Inc."),
    ("ADSK", "Autodesk, Inc."),
    ("NFLX", "Netflix, Inc."),
    ("FISV", "Fiserv, Inc."),
    ("PAYX", "Paychex, Inc."),
    ("ORLY", "O'Reilly Automotive, Inc."),
    ("ANSS", "ANSYS, Inc."),
    ("MRNA", "Moderna, Inc."),
    ("SPLK", "Splunk Inc."),
    ("NVDA", "NVIDIA Corporation"),
    ("MRVL", "Marvell Technology Group Ltd."),
    ("ROST", "Ross Stores, Inc."),
    ("PDD", "Pinduoduo Inc."),
    ("AMD", "Advanced Micro Devices, Inc."),
    ("AEP", "American Electric Power Company, Inc."),
    ("TEAM", "Atlassian Corporation Plc"),
    ("FANG", "Diamondback Energy, Inc."),
    ("SGEN", "Seagen Inc."),
    ("ADBE", "Adobe Inc."),
    ("CSGP", "CoStar Group, Inc."),
    ("AZN", "AstraZeneca PLC"),
    ("ALGN", "Align Technology, Inc."),
    ("TMUS", "T-Mobile US, Inc."),
    ("WBD", "Wider Inc."),
    ("MU", "Micron Technology, Inc."),
    ("PEP", "PepsiCo, Inc."),
    ("FB", "Facebook, Inc."),
    ("PANW", "Palo Alto Networks, Inc."),
    ("GOOGL", "Alphabet Inc."),
    ("BIIB", "Biogen Inc."),
    ("GILD", "Gilead Sciences, Inc."),
    ("MELI", "MercadoLibre, Inc."),
    ("DXCM", "DexCom, Inc."),
    ("CTAS", "Cintas Corporation"),
    ("ADP", "Automatic Data Processing, Inc."),
];
